# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Computational Discovery on Jupyter
author: Neil J. Calkin, Eunice Y.S. Chan, and Robert M. Corless
copyright: "2022"
logo: logo.jpg
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context


# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Launch button settings
launch_buttons:
  notebook_interface: classic
  binderhub_url: ""
  jupyterhub_url: ""
  thebe: false
  colab_url: ""

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon: "logo.jpg"
  use_issues_button: false
  use_repository_button: true
  use_edit_page_button: true

repository:
  url: https://github.com/Computational-Discovery-on-Jupyter/Computational-Discovery-on-Jupyter  # The URL to your book's repository
  path_to_book: "book"  # A path to your book's folder, relative to the repository root.
  branch: master  # Which branch of the repository should be used when creating links

sphinx:
  config:
    bibtex_reference_style: author_year
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  extra_extensions:
    - sphinx_proof
